//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleChartAppl
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NorthwindEntities : DbContext
    {
        public NorthwindEntities()
            : base("name=NorthwindEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category_Sales_for_1997> Category_Sales_for_1997 { get; set; }
    
        public virtual ObjectResult<CountOfSuppliersByCountry_Result> CountOfSuppliersByCountry()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CountOfSuppliersByCountry_Result>("CountOfSuppliersByCountry");
        }
    
        public virtual ObjectResult<U_CategoryWiseSales_1996_1997_Result> U_CategoryWiseSales_1996_1997()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<U_CategoryWiseSales_1996_1997_Result>("U_CategoryWiseSales_1996_1997");
        }
    
        public virtual ObjectResult<CategoryWiseSales_1996_1997_Result> CategoryWiseSales_1996_1997()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CategoryWiseSales_1996_1997_Result>("CategoryWiseSales_1996_1997");
        }
    
        public virtual ObjectResult<U_CategoryWiseTotalSales_1996_1997_Result> U_CategoryWiseTotalSales_1996_1997()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<U_CategoryWiseTotalSales_1996_1997_Result>("U_CategoryWiseTotalSales_1996_1997");
        }
    }
}
